version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-central-1:601912882130:task-definition/spring-boot-rest-hello-world-td:1"
        LoadBalancerInfo:
          ContainerName: "spring-boot-rest-hello-world"
          ContainerPort: 8080
        # Optional properties
        PlatformVersion: "LATEST"
